name: Test-env-deployment
on:
  pull_request:
    types:
      - opened
    branches:
      - Test
jobs:
  test:
    if: github.event.pull_request.base.ref == 'Test' && github.event.pull_request.merged == true
    runs-on: windows-latest
    environment: development

    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

    # Runs a single command using the runners shell
      - name: Synapse workspace deployment
        uses: Azure/Synapse-workspace-deployment@V1.8.0
            
        with:
          TargetWorkspaceName: 'synapse-fdr-test'
          TemplateFile: './synapse-fdr/TemplateForWorkspace.json'
          ParametersFile: './synapse-fdr/TemplateParametersForWorkspace.json'
          #OverrideArmParameters: './parameters/testparameters.yaml'
          environment: 'Azure Public'
          resourceGroup: 'rg-c2s-internal-0010'
          clientId: ${{secrets.AZURE_CLIENT_ID}}
          clientSecret: ${{secrets.AZURE_CLIENT_SECRET}}
          subscriptionId: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          tenantId: ${{secrets.AZURE_TENANT_ID}}
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
